name:          Code Guide par @mdo
description:   Standards pour un code HTML et CSS flexible et durable.
url:           http://mdo.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
